local lovely = require("lovely")
local nativefs = require("nativefs")



Brainstorm.SearchTagList = {
	["None"]="",
	["Uncommon Tag"]="tag_uncommon",
	["Rare Tag"]="tag_rare",
	["Holographic Tag"]="tag_holo",
  ["Foil Tag"]="tag_foil",
	["Polychrome Tag"]="tag_polychrome",
	["Investment Tag"]="tag_investment",
	["Voucher Tag"]="tag_voucher",
	["Boss Tag"]="tag_boss",
	["Charm Tag"]="tag_charm",
	["Juggle Tag"]="tag_juggle",
	["Double Tag"]="tag_double",
	["Coupon Tag"]="tag_coupon",
	["Economy Tag"]="tag_economy",
	["Skip Tag"]="tag_skip",
	["D6 Tag"]="tag_d_six",
}

Brainstorm.SearchPackList = {
	["None"] = {},
	["Arcana"] = {"p_arcana_normal_1","p_arcana_normal_2","p_arcana_normal_3","p_arcana_normal_4","p_arcana_jumbo_1","p_arcana_jumbo_2","p_arcana_mega_1", "p_arcana_mega_2"},
	["Celestial"] = {"p_celestial_normal_1","p_celestial_normal_2","p_celestial_normal_3","p_celestial_normal_4","p_celestial_jumbo_1","p_celestial_jumbo_2","p_celestial_mega_1", "p_celestial_mega_2"},
	["Standard"] = {"p_standard_normal_1","p_standard_normal_2","p_standard_normal_3","p_standard_normal_4","p_standard_jumbo_1","p_standard_jumbo_2","p_standard_mega_1", "p_standard_mega_2"},
	["Buffoon"] = {"p_buffoon_normal_1","p_buffoon_normal_2","p_buffoon_jumbo_1","p_buffoon_mega_1"},
	["Spectral"] = {"p_spectral_normal_1","p_spectral_normal_2","p_spectral_jumbo_1","p_spectral_mega_1"},
	["Normal Arcana"] = {"p_arcana_normal_1","p_arcana_normal_2","p_arcana_normal_3","p_arcana_normal_4"},
	["Jumbo Arcana"] = {"p_arcana_jumbo_1","p_arcana_jumbo_2"},
	["Mega Arcana"] = {"p_arcana_mega_1", "p_arcana_mega_2"},
	["Normal Celestial"] = {"p_celestial_normal_1","p_celestial_normal_2","p_celestial_normal_3","p_celestial_normal_4"},
	["Jumbo Celestial"] = {"p_celestial_jumbo_1","p_celestial_jumbo_2"},
	["Mega Celestial"] = {"p_celestial_mega_1", "p_celestial_mega_2"},
	["Normal Standard"] = {"p_standard_normal_1","p_standard_normal_2","p_standard_normal_3","p_standard_normal_4"},
	["Jumbo Standard"] = {"p_standard_jumbo_1","p_standard_jumbo_2"},
	["Mega Standard"] = {"p_standard_mega_1", "p_standard_mega_2"},
	["Normal Buffoon"] = {"p_buffoon_normal_1","p_buffoon_normal_2"},
	["Jumbo Buffoon"] = {"p_buffoon_jumbo_1"},
	["Mega Buffoon"] = {"p_buffoon_mega_1"},
	["Normal Spectral"] = {"p_spectral_normal_1","p_spectral_normal_2"},
	["Jumbo Spectral"] = {"p_spectral_jumbo_1"},
	["Mega Spectral"] = {"p_spectral_mega_1"},
}

Brainstorm.SearchJokerList = {
	["None"] = "",
	["8 Ball"] = "j_8_ball",
	["Abstract Joker"] = "j_abstract",
	["Acrobat"] = "j_acrobat",
	["Ancient Joker"] = "j_ancient",
	["Arrowhead"] = "j_arrowhead",
	["Astronomer"] = "j_astronomer",
	["Banner"] = "j_banner",
	["Baron"] = "j_baron",
	["Baseball Card"] = "j_baseball",
	["Blackboard"] = "j_blackboard",
	["Bloodstone"] = "j_bloodstone",
	["Blue Joker"] = "j_blue_joker",
	["Blueprint"] = "j_blueprint",
	["Bootstraps"] = "j_bootstraps",
	["Brainstorm"] = "j_brainstorm",
	["Bull"] = "j_bull",
	["Burglar"] = "j_burglar",
	["Burnt Joker"] = "j_burnt",
	["Business Card"] = "j_business",
	["Caino"] = "j_caino",
	["Campfire"] = "j_campfire",
	["Card Sharp"] = "j_card_sharp",
	["Cartomancer"] = "j_cartomancer",
	["Castle"] = "j_castle",
	["Cavendish"] = "j_cavendish",
	["Ceremonial Dagger"] = "j_ceremonial",
	["Certificate"] = "j_certificate",
	["Chaos the Clown"] = "j_chaos",
	["Chicot"] = "j_chicot",
	["Clever Joker"] = "j_clever",
	["Cloud 9"] = "j_cloud_9",
	["Constellation"] = "j_constellation",
	["Crafty Joker"] = "j_crafty",
	["Crazy Joker"] = "j_crazy",
	["Credit Card"] = "j_credit_card",
	["Delayed Gratification"] = "j_delayed_grat",
	["Devious Joker"] = "j_devious",
	["Diet Cola"] = "j_diet_cola",
	["DNA"] = "j_dna",
	["Driver's License"] = "j_drivers_license",
	["Droll Joker"] = "j_droll",
	["Drunkard"] = "j_drunkard",
	["Dusk"] = "j_dusk",
	["Egg"] = "j_egg",
	["Erosion"] = "j_erosion",
	["Even Steven"] = "j_even_steven",
	["Faceless Joker"] = "j_faceless",
	["Fibonacci"] = "j_fibonacci",
	["Flash Card"] = "j_flash",
	["Flower Pot"] = "j_flower_pot",
	["Fortune Teller"] = "j_fortune_teller",
	["Four Fingers"] = "j_four_fingers",
	["Gift Card"] = "j_gift",
	["Glass Joker"] = "j_glass",
	["Gluttonous Joker"] = "j_gluttenous_joker",
	["Golden Joker"] = "j_golden",
	["Golden Ticket"] = "j_ticket",
	["Green Joker"] = "j_green_joker",
	["Greedy Joker"] = "j_greedy_joker",
	["Gros Michel"] = "j_gros_michel",
	["Hack"] = "j_hack",
	["Half Joker"] = "j_half",
	["Hallucination"] = "j_hallucination",
	["Hanging Chad"] = "j_hanging_chad",
	["Hiker"] = "j_hiker",
	["Hit the Road"] = "j_hit_the_road",
	["Hologram"] = "j_hologram",
	["Ice Cream"] = "j_ice_cream",
	["Invisible Joker"] = "j_invisible",
	["Joker"] = "j_joker",
	["Joker Stencil"] = "j_stencil",
	["Jolly Joker"] = "j_jolly",
	["Juggler"] = "j_juggler",
	["Luchador"] = "j_luchador",
	["Lucky Cat"] = "j_lucky_cat",
	["Lusty Joker"] = "j_lusty_joker",
	["Mad Joker"] = "j_mad",
	["Madness"] = "j_madness",
	["Mail-In Rebate"] = "j_mail",
	["Marble Joker"] = "j_marble",
	["Matador"] = "j_matador",
	["Merry Andy"] = "j_merry_andy",
	["Midas Mask"] = "j_midas_mask",
	["Mime"] = "j_mime",
	["Misprint"] = "j_misprint",
	["Mr. Bones"] = "j_mr_bones",
	["Mystic Summit"] = "j_mystic_summit",
	["Obelisk"] = "j_obelisk",
	["Odd Todd"] = "j_odd_todd",
	["Onyx Agate"] = "j_onyx_agate",
	["Oops! All 6s"] = "j_oops",
	["Pareidolia"] = "j_pareidolia",
	["Perkeo"] = "j_perkeo",
	["Photograph"] = "j_photograph",
	["Popcorn"] = "j_popcorn",
	["Raised Fist"] = "j_raised_fist",
	["Ramen"] = "j_ramen",
	["Red Card"] = "j_red_card",
	["Reserved Parking"] = "j_reserved_parking",
	["Ride the Bus"] = "j_ride_the_bus",
	["Riff-raff"] = "j_riff_raff",
	["Rocket"] = "j_rocket",
	["Rough Gem"] = "j_rough_gem",
	["Runner"] = "j_runner",
	["Satellite"] = "j_satellite",
	["Scary Face"] = "j_scary_face",
	["Scholar"] = "j_scholar",
	["Seance"] = "j_seance",
	["Seeing Double"] = "j_seeing_double",
	["Seltzer"] = "j_selzer",
	["Shoot the Moon"] = "j_shoot_the_moon",
	["Shortcut"] = "j_shortcut",
	["Showman"] = "j_ring_master",
	["Sixth Sense"] = "j_sixth_sense",
	["Sly Joker"] = "j_sly",
	["Smeared Joker"] = "j_smeared",
	["Smiley Face"] = "j_smiley",
	["Sock and Buskin"] = "j_sock_and_buskin",
	["Space Joker"] = "j_space",
	["Spare Trousers"] = "j_trousers",
	["Splash"] = "j_splash",
	["Square Joker"] = "j_square",
	["Steel Joker"] = "j_steel_joker",
	["Stone Joker"] = "j_stone",
	["Stuntman"] = "j_stuntman",
	["Supernova"] = "j_supernova",
	["Superposition"] = "j_superposition",
	["Swashbuckler"] = "j_swashbuckler",
	["The Duo"] = "j_duo",
	["The Family"] = "j_family",
	["The Idol"] = "j_idol",
	["The Order"] = "j_order",
	["The Tribe"] = "j_tribe",
	["The Trio"] = "j_trio",
	["Throwback"] = "j_throwback",
	["To Do List"] = "j_todo_list",
	["To the Moon"] = "j_to_the_moon",
	["Trading Card"] = "j_trading",
	["Triboulet"] = "j_triboulet",
	["Troubadour"] = "j_troubadour",
	["Turtle Bean"] = "j_turtle_bean",
	["Vagabond"] = "j_vagabond",
	["Vampire"] = "j_vampire",
	["Walkie Talkie"] = "j_walkie_talkie",
	["Wee Joker"] = "j_wee",
	["Wily Joker"] = "j_wily",
	["Wrathful Joker"] = "j_wrathful_joker",
	["Yorick"] = "j_yorick",
	["Zany Joker"] = "j_zany",
}
Brainstorm.seedsPerFrame = {
    ["500"] = 500,
    ["750"] = 750,
    ["1000"] = 1000,
}

local searchTagKeys = {"None", "Charm Tag", "Double Tag", "Uncommon Tag", "Rare Tag", "Holographic Tag", "Foil Tag", "Polychrome Tag", "Investment Tag", "Voucher Tag", "Boss Tag", "Juggle Tag", "Coupon Tag", "Economy Tag", "Skip Tag", "D6 Tag"}
local searchPackKeys = {"None", "Arcana", "Celestial", "Standard", "Buffoon", "Spectral", "Normal Arcana", "Jumbo Arcana", "Mega Arcana", "Normal Celestial", "Jumbo Celestial", "Mega Celestial", "Normal Standard", "Jumbo Standard", "Mega Standard", "Normal Buffoon", "Jumbo Buffoon", "Mega Buffoon", "Normal Spectral", "Jumbo Spectral", "Mega Spectral"}
local searchJokerKeys = {"None", "8 Ball", "Abstract Joker", "Acrobat", "Ancient Joker", "Arrowhead", "Astronomer", "Banner", "Baron", "Baseball Card", "Blackboard", "Bloodstone", "Blue Joker", "Blueprint", "Bootstraps", "Brainstorm", "Bull", "Burglar", "Burnt Joker", "Business Card", "Caino", "Campfire", "Card Sharp", "Cartomancer", "Castle", "Cavendish", "Ceremonial Dagger", "Certificate", "Chaos the Clown", "Chicot", "Clever Joker", "Cloud 9", "Constellation", "Crafty Joker", "Crazy Joker", "Credit Card", "Delayed Gratification", "Devious Joker", "Diet Cola", "DNA", "Driver's License", "Droll Joker", "Drunkard", "Dusk", "Egg", "Erosion", "Even Steven", "Faceless Joker", "Fibonacci", "Flash Card", "Flower Pot", "Fortune Teller", "Four Fingers", "Gift Card", "Glass Joker", "Gluttonous Joker", "Golden Joker", "Golden Ticket", "Green Joker", "Greedy Joker", "Gros Michel", "Hack", "Half Joker", "Hallucination", "Hanging Chad", "Hiker", "Hit the Road", "Hologram", "Ice Cream", "Invisible Joker", "Joker", "Joker Stencil", "Jolly Joker", "Juggler", "Luchador", "Lucky Cat", "Lusty Joker", "Mad Joker", "Madness", "Mail-In Rebate", "Marble Joker", "Matador", "Merry Andy", "Midas Mask", "Mime", "Misprint", "Mr. Bones", "Mystic Summit", "Obelisk", "Odd Todd", "Onyx Agate", "Oops! All 6s", "Pareidolia", "Perkeo", "Photograph", "Popcorn", "Raised Fist", "Ramen", "Red Card", "Reserved Parking", "Ride the Bus", "Riff-raff", "Rocket", "Rough Gem", "Runner", "Satellite", "Scary Face", "Scholar", "Seance", "Seeing Double", "Seltzer", "Shoot the Moon", "Shortcut", "Showman", "Sixth Sense", "Sly Joker", "Smeared Joker", "Smiley Face", "Sock and Buskin", "Space Joker", "Spare Trousers", "Splash", "Square Joker", "Steel Joker", "Stone Joker", "Stuntman", "Supernova", "Superposition", "Swashbuckler", "The Duo", "The Family", "The Idol", "The Order", "The Tribe", "The Trio", "Throwback", "To Do List", "To the Moon", "Trading Card", "Triboulet", "Troubadour", "Turtle Bean", "Vagabond", "Vampire", "Walkie Talkie", "Wee Joker", "Wily Joker", "Wrathful Joker", "Yorick", "Zany Joker"}
local seedsPerFrame = {"500", "750", "1000"}
-- print(Brainstorm.FUNCS.inspect(searchTagKeys))

Brainstorm.G_FUNCS_options_ref = G.FUNCS.options
G.FUNCS.options = function(e)
	Brainstorm.G_FUNCS_options_ref(e)
end
local ct = create_tabs
function create_tabs(args)
	if args and args.tab_h == 7.05 then
		args.tabs[#args.tabs + 1] = {
			label = "Brainstorm",
			tab_definition_function = function()
				return {
					n = G.UIT.ROOT,
					config = {
						align = "cm",
						padding = 0.05,
						colour = G.C.CLEAR,
					},
					nodes = {
						create_toggle({
							label = "Debug Mode",
							ref_table = Brainstorm.SETTINGS,
							ref_value = "debug_mode",
							callback = function(_set_toggle)
								_RELEASE_MODE = not Brainstorm.SETTINGS.debug_mode
								G.F_NO_ACHIEVEMENTS = Brainstorm.SETTINGS.debug_mode
							end,
						}),
						create_option_cycle({
							label = "AutoReroll Search Tag",
							scale = 0.8,
							w = 4,
							options = searchTagKeys,
							opt_callback = "change_search_tag",
							current_option = Brainstorm.SETTINGS.autoreroll.searchTagID or 1,
						}),
						create_option_cycle({
							label = "AutoReroll Search Pack",
							scale = 0.8,
							w = 4,
							options = searchPackKeys,
							opt_callback = "change_search_pack",
							current_option = Brainstorm.SETTINGS.autoreroll.searchPackID or 1,
						}),
						create_option_cycle({
							label = "AutoReroll Search Joker",
							scale = 0.8,
							w = 4,
							options = searchJokerKeys,
							opt_callback = "change_search_joker",
							current_option = Brainstorm.SETTINGS.autoreroll.searchJokerID or 1,
						}),
						create_option_cycle({
							label = "Charm Tag/Arcana Pack: Number of Souls",
							scale = 0.8,
							w = 4,
							options = {0,1,2},
							opt_callback = "change_search_soul_count",
							current_option = Brainstorm.SETTINGS.autoreroll.searchForSoul + 1 or 1,
						}),
                        create_option_cycle({
							label = "Rerolls per Frame",
							scale = 0.8,
							w = 4,
							options = seedsPerFrame,
							opt_callback = "change_seeds_per_frame",
							current_option = Brainstorm.SETTINGS.autoreroll.seedsPerFrameID or 1,
						}),
					},
				}
			end,
			tab_definition_function_args = "Brainstorm",
		}
	end
	return ct(args)
end
function saveManagerAlert(text)
	G.E_MANAGER:add_event(Event({
		trigger = "after",
		delay = 0.4,
		func = function()
			attention_text({
				text = text,
				scale = 0.7,
				hold = 3,
				major = G.STAGE == G.STAGES.RUN and G.play or G.title_top,
				backdrop_colour = G.C.SECONDARY_SET.Tarot,
				align = "cm",
				offset = {
					x = 0,
					y = -3.5,
				},
				silent = true,
			})
			G.E_MANAGER:add_event(Event({
				trigger = "after",
				delay = 0.06 * G.SETTINGS.GAMESPEED,
				blockable = false,
				blocking = false,
				func = function()
					play_sound("other1", 0.76, 0.4)
					return true
				end,
			}))
			return true
		end,
	}))
end
