// #include "items.hpp"

// std::vector<Item> ENHANCEMENTS = {
//     Item::Bonus_Card, Item::Mult_Card,  Item::Wild_Card, Item::Glass_Card,
//     Item::Steel_Card, Item::Stone_Card, Item::Gold_Card, Item::Lucky_Card};

// std::vector<Item> CARDS = {
//     Item::C_2, Item::C_3, Item::C_4, Item::C_5, Item::C_6, Item::C_7,
//     Item::C_8, Item::C_9, Item::C_A, Item::C_J, Item::C_K, Item::C_Q,
//     Item::C_T, Item::D_2, Item::D_3, Item::D_4, Item::D_5, Item::D_6,
//     Item::D_7, Item::D_8, Item::D_9, Item::D_A, Item::D_J, Item::D_K,
//     Item::D_Q, Item::D_T, Item::H_2, Item::H_3, Item::H_4, Item::H_5,
//     Item::H_6, Item::H_7, Item::H_8, Item::H_9, Item::H_A, Item::H_J,
//     Item::H_K, Item::H_Q, Item::H_T, Item::S_2, Item::S_3, Item::S_4,
//     Item::S_5, Item::S_6, Item::S_7, Item::S_8, Item::S_9, Item::S_A,
//     Item::S_J, Item::S_K, Item::S_Q, Item::S_T};

// std::vector<Item> SUITS = {Item::Spades, Item::Hearts, Item::Clubs,
//                            Item::Diamonds};

// std::vector<Item> RANKS = {Item::_2,  Item::_3,   Item::_4,    Item::_5,
//                            Item::_6,  Item::_7,   Item::_8,    Item::_9,
//                            Item::_10, Item::Jack, Item::Queen, Item::King,
//                            Item::Ace};

// std::vector<WeightedItem> PACKS = {
//     WeightedItem(Item::RETRY, 22.42), // total
//     WeightedItem(Item::Arcana_Pack, 4),
//     WeightedItem(Item::Jumbo_Arcana_Pack, 2),
//     WeightedItem(Item::Mega_Arcana_Pack, 0.5),
//     WeightedItem(Item::Celestial_Pack, 4),
//     WeightedItem(Item::Jumbo_Celestial_Pack, 2),
//     WeightedItem(Item::Mega_Celestial_Pack, 0.5),
//     WeightedItem(Item::Standard_Pack, 4),
//     WeightedItem(Item::Jumbo_Standard_Pack, 2),
//     WeightedItem(Item::Mega_Standard_Pack, 0.5),
//     WeightedItem(Item::Buffoon_Pack, 1.2),
//     WeightedItem(Item::Jumbo_Buffoon_Pack, 0.6),
//     WeightedItem(Item::Mega_Buffoon_Pack, 0.15),
//     WeightedItem(Item::Spectral_Pack, 0.6),
//     WeightedItem(Item::Jumbo_Spectral_Pack, 0.3),
//     WeightedItem(Item::Mega_Spectral_Pack, 0.07)};

// std::vector<Item> TAROTS = {Item::The_Fool,
//                             Item::The_Magician,
//                             Item::The_High_Priestess,
//                             Item::The_Empress,
//                             Item::The_Emperor,
//                             Item::The_Hierophant,
//                             Item::The_Lovers,
//                             Item::The_Chariot,
//                             Item::Justice,
//                             Item::The_Hermit,
//                             Item::The_Wheel_of_Fortune,
//                             Item::Strength,
//                             Item::The_Hanged_Man,
//                             Item::Death,
//                             Item::Temperance,
//                             Item::The_Devil,
//                             Item::The_Tower,
//                             Item::The_Star,
//                             Item::The_Moon,
//                             Item::The_Sun,
//                             Item::Judgement,
//                             Item::The_World};

// std::vector<Item> PLANETS = {Item::Mercury,  Item::Venus,   Item::Earth,
//                              Item::Mars,     Item::Jupiter, Item::Saturn,
//                              Item::Uranus,   Item::Neptune, Item::Pluto,
//                              Item::Planet_X, Item::Ceres,   Item::Eris};

// std::vector<Item> COMMON_JOKERS_100 = {Item::Joker,
//                                        Item::Greedy_Joker,
//                                        Item::Lusty_Joker,
//                                        Item::Wrathful_Joker,
//                                        Item::Gluttonous_Joker,
//                                        Item::Jolly_Joker,
//                                        Item::Zany_Joker,
//                                        Item::Mad_Joker,
//                                        Item::Crazy_Joker,
//                                        Item::Droll_Joker,
//                                        Item::Sly_Joker,
//                                        Item::Wily_Joker,
//                                        Item::Clever_Joker,
//                                        Item::Devious_Joker,
//                                        Item::Crafty_Joker,
//                                        Item::Half_Joker,
//                                        Item::Credit_Card,
//                                        Item::Banner,
//                                        Item::Mystic_Summit,
//                                        Item::_8_Ball,
//                                        Item::Misprint,
//                                        Item::Raised_Fist,
//                                        Item::Chaos_the_Clown,
//                                        Item::Scary_Face,
//                                        Item::Abstract_Joker,
//                                        Item::Delayed_Gratification,
//                                        Item::Gros_Michel,
//                                        Item::Even_Steven,
//                                        Item::Odd_Todd,
//                                        Item::Scholar,
//                                        Item::Business_Card,
//                                        Item::Supernova,
//                                        Item::Ride_the_Bus,
//                                        Item::Egg,
//                                        Item::Runner,
//                                        Item::Ice_Cream,
//                                        Item::Splash,
//                                        Item::Blue_Joker,
//                                        Item::Faceless_Joker,
//                                        Item::Green_Joker,
//                                        Item::Superposition,
//                                        Item::To_Do_List,
//                                        Item::Cavendish,
//                                        Item::Red_Card,
//                                        Item::Square_Joker,
//                                        Item::Riff_raff,
//                                        Item::Photograph,
//                                        Item::Mail_In_Rebate,
//                                        Item::Hallucination,
//                                        Item::Fortune_Teller,
//                                        Item::Juggler,
//                                        Item::Drunkard,
//                                        Item::Golden_Joker,
//                                        Item::Popcorn,
//                                        Item::Walkie_Talkie,
//                                        Item::Smiley_Face,
//                                        Item::Golden_Ticket,
//                                        Item::Swashbuckler,
//                                        Item::Hanging_Chad,
//                                        Item::Shoot_the_Moon};

// std::vector<Item> COMMON_JOKERS = {
//     Item::Joker,
//     Item::Greedy_Joker,
//     Item::Lusty_Joker,
//     Item::Wrathful_Joker,
//     Item::Gluttonous_Joker,
//     Item::Jolly_Joker,
//     Item::Zany_Joker,
//     Item::Mad_Joker,
//     Item::Crazy_Joker,
//     Item::Droll_Joker,
//     Item::Sly_Joker,
//     Item::Wily_Joker,
//     Item::Clever_Joker,
//     Item::Devious_Joker,
//     Item::Crafty_Joker,
//     Item::Half_Joker,
//     Item::Credit_Card,
//     Item::Banner,
//     Item::Mystic_Summit,
//     Item::_8_Ball,
//     Item::Misprint,
//     Item::Raised_Fist,
//     Item::Chaos_the_Clown,
//     Item::Scary_Face,
//     Item::Abstract_Joker,
//     Item::Delayed_Gratification,
//     Item::Gros_Michel,
//     Item::Even_Steven,
//     Item::Odd_Todd,
//     Item::Scholar,
//     Item::Business_Card,
//     Item::Supernova,
//     Item::Ride_the_Bus,
//     Item::Egg,
//     Item::Runner,
//     Item::Ice_Cream,
//     Item::Splash,
//     Item::Blue_Joker,
//     Item::Faceless_Joker,
//     Item::Green_Joker,
//     Item::Superposition,
//     Item::To_Do_List,
//     Item::Cavendish,
//     Item::Red_Card,
//     Item::Square_Joker,
//     Item::Riff_raff,
//     Item::Photograph,
//     Item::Reserved_Parking,
//     Item::Mail_In_Rebate,
//     Item::Hallucination,
//     Item::Fortune_Teller,
//     Item::Juggler,
//     Item::Drunkard,
//     Item::Golden_Joker,
//     Item::Popcorn,
//     Item::Walkie_Talkie,
//     Item::Smiley_Face,
//     Item::Golden_Ticket,
//     Item::Swashbuckler,
//     Item::Hanging_Chad,
//     Item::Shoot_the_Moon,
// };

// std::vector<Item> UNCOMMON_JOKERS_100 = {
//     Item::Joker_Stencil, Item::Four_Fingers,
//     Item::Mime,          Item::Ceremonial_Dagger,
//     Item::Marble_Joker,  Item::Loyalty_Card,
//     Item::Dusk,          Item::Fibonacci,
//     Item::Steel_Joker,   Item::Hack,
//     Item::Pareidolia,    Item::Space_Joker,
//     Item::Burglar,       Item::Blackboard,
//     Item::Constellation, Item::Hiker,
//     Item::Card_Sharp,    Item::Madness,
//     Item::Vampire,       Item::Shortcut,
//     Item::Hologram,      Item::Vagabond,
//     Item::Cloud_9,       Item::Rocket,
//     Item::Midas_Mask,    Item::Luchador,
//     Item::Gift_Card,     Item::Turtle_Bean,
//     Item::Erosion,       Item::Reserved_Parking,
//     Item::To_the_Moon,   Item::Stone_Joker,
//     Item::Lucky_Cat,     Item::Bull,
//     Item::Diet_Cola,     Item::Trading_Card,
//     Item::Flash_Card,    Item::Spare_Trousers,
//     Item::Ramen,         Item::Seltzer,
//     Item::Castle,        Item::Mr_Bones,
//     Item::Acrobat,       Item::Sock_and_Buskin,
//     Item::Troubadour,    Item::Certificate,
//     Item::Smeared_Joker, Item::Throwback,
//     Item::Rough_Gem,     Item::Bloodstone,
//     Item::Arrowhead,     Item::Onyx_Agate,
//     Item::Glass_Joker,   Item::Showman,
//     Item::Flower_Pot,    Item::Merry_Andy,
//     Item::Oops_All_6s,   Item::The_Idol,
//     Item::Seeing_Double, Item::Matador,
//     Item::Stuntman,      Item::Satellite,
//     Item::Cartomancer,   Item::Astronomer,
//     Item::Burnt_Joker,   Item::Bootstraps};

// std::vector<Item> UNCOMMON_JOKERS = {
//     Item::Joker_Stencil, Item::Four_Fingers,
//     Item::Mime,          Item::Ceremonial_Dagger,
//     Item::Marble_Joker,  Item::Loyalty_Card,
//     Item::Dusk,          Item::Fibonacci,
//     Item::Steel_Joker,   Item::Hack,
//     Item::Pareidolia,    Item::Space_Joker,
//     Item::Burglar,       Item::Blackboard,
//     Item::Sixth_Sense,   Item::Constellation,
//     Item::Hiker,         Item::Card_Sharp,
//     Item::Madness,       Item::Seance,
//     Item::Vampire,       Item::Shortcut,
//     Item::Hologram,      Item::Cloud_9,
//     Item::Rocket,        Item::Midas_Mask,
//     Item::Luchador,      Item::Gift_Card,
//     Item::Turtle_Bean,   Item::Erosion,
//     Item::To_the_Moon,   Item::Stone_Joker,
//     Item::Lucky_Cat,     Item::Bull,
//     Item::Diet_Cola,     Item::Trading_Card,
//     Item::Flash_Card,    Item::Spare_Trousers,
//     Item::Ramen,         Item::Seltzer,
//     Item::Castle,        Item::Mr_Bones,
//     Item::Acrobat,       Item::Sock_and_Buskin,
//     Item::Troubadour,    Item::Certificate,
//     Item::Smeared_Joker, Item::Throwback,
//     Item::Rough_Gem,     Item::Bloodstone,
//     Item::Arrowhead,     Item::Onyx_Agate,
//     Item::Glass_Joker,   Item::Showman,
//     Item::Flower_Pot,    Item::Merry_Andy,
//     Item::Oops_All_6s,   Item::The_Idol,
//     Item::Seeing_Double, Item::Matador,
//     Item::Satellite,     Item::Cartomancer,
//     Item::Astronomer,    Item::Bootstraps,
// };

// std::vector<Item> RARE_JOKERS_100 = {Item::DNA,
//                                      Item::Sixth_Sense,
//                                      Item::Seance,
//                                      Item::Baron,
//                                      Item::Obelisk,
//                                      Item::Baseball_Card,
//                                      Item::Ancient_Joker,
//                                      Item::Campfire,
//                                      Item::Blueprint,
//                                      Item::Wee_Joker,
//                                      Item::Hit_the_Road,
//                                      Item::The_Duo,
//                                      Item::The_Trio,
//                                      Item::The_Family,
//                                      Item::The_Order,
//                                      Item::The_Tribe,
//                                      Item::Invisible_Joker,
//                                      Item::Brainstorm,
//                                      Item::Drivers_License};

// std::vector<Item> RARE_JOKERS = {
//     Item::DNA,
//     Item::Vagabond,
//     Item::Baron,
//     Item::Obelisk,
//     Item::Baseball_Card,
//     Item::Ancient_Joker,
//     Item::Campfire,
//     Item::Blueprint,
//     Item::Wee_Joker,
//     Item::Hit_the_Road,
//     Item::The_Duo,
//     Item::The_Trio,
//     Item::The_Family,
//     Item::The_Order,
//     Item::The_Tribe,
//     Item::Stuntman,
//     Item::Invisible_Joker,
//     Item::Brainstorm,
//     Item::Drivers_License,
//     Item::Burnt_Joker,
// };

// std::vector<Item> LEGENDARY_JOKERS = {Item::Canio, Item::Triboulet,
//                                       Item::Yorick, Item::Chicot,
//                                       Item::Perkeo};

// std::vector<Item> VOUCHERS = {
//     Item::Overstock,       Item::Overstock_Plus, Item::Clearance_Sale,
//     Item::Liquidation,     Item::Hone,           Item::Glow_Up,
//     Item::Reroll_Surplus,  Item::Reroll_Glut,    Item::Crystal_Ball,
//     Item::Omen_Globe,      Item::Telescope,      Item::Observatory,
//     Item::Grabber,         Item::Nacho_Tong,     Item::Wasteful,
//     Item::Recyclomancy,    Item::Tarot_Merchant, Item::Tarot_Tycoon,
//     Item::Planet_Merchant, Item::Planet_Tycoon,  Item::Seed_Money,
//     Item::Money_Tree,      Item::Blank,          Item::Antimatter,
//     Item::Magic_Trick,     Item::Illusion,       Item::Hieroglyph,
//     Item::Petroglyph,      Item::Directors_Cut,  Item::Retcon,
//     Item::Paint_Brush,     Item::Palette};

// std::vector<Item> SPECTRALS = {
//     Item::Familiar,  Item::Grim,     Item::Incantation, Item::Talisman,
//     Item::Aura,      Item::Wraith,   Item::Sigil,       Item::Ouija,
//     Item::Ectoplasm, Item::Immolate, Item::Ankh,        Item::Deja_Vu,
//     Item::Hex,       Item::Trance,   Item::Medium,      Item::Cryptid,
//     Item::RETRY, // Soul
//     Item::RETRY  // Black_Hole
// };

// std::vector<Item> TAGS = {
//     Item::Uncommon_Tag,   Item::Rare_Tag,        Item::Negative_Tag,
//     Item::Foil_Tag,       Item::Holographic_Tag, Item::Polychrome_Tag,
//     Item::Investment_Tag, Item::Voucher_Tag,     Item::Boss_Tag,
//     Item::Standard_Tag,   Item::Charm_Tag,       Item::Meteor_Tag,
//     Item::Buffoon_Tag,    Item::Handy_Tag,       Item::Garbage_Tag,
//     Item::Ethereal_Tag,   Item::Coupon_Tag,      Item::Double_Tag,
//     Item::Juggle_Tag,     Item::D6_Tag,          Item::Top_up_Tag,
//     Item::Speed_Tag,      Item::Orbital_Tag,     Item::Economy_Tag};

// std::vector<Item> BOSSES = {
//     Item::The_Arm,      Item::The_Club,      Item::The_Eye,
//     Item::Amber_Acorn,  Item::Cerulean_Bell, Item::Crimson_Heart,
//     Item::Verdant_Leaf, Item::Violet_Vessel, Item::The_Fish,
//     Item::The_Flint,    Item::The_Goad,      Item::The_Head,
//     Item::The_Hook,     Item::The_House,     Item::The_Manacle,
//     Item::The_Mark,     Item::The_Mouth,     Item::The_Needle,
//     Item::The_Ox,       Item::The_Pillar,    Item::The_Plant,
//     Item::The_Psychic,  Item::The_Serpent,   Item::The_Tooth,
//     Item::The_Wall,     Item::The_Water,     Item::The_Wheel,
//     Item::The_Window};
